# Generated by Django 3.0.5 on 2021-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_productpresenting_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Stock Maximo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Stock Minimo'),
        ),
        migrations.AlterField(
            model_name='productpresenting',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='productpresenting',
            name='quantity_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Cantidad Minima'),
        ),
    ]
