# Generated by Django 3.0.5 on 2021-03-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20210311_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Stock'),
        ),
    ]
