# Generated by Django 3.0.5 on 2021-03-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casing',
            name='user',
        ),
    ]
