# Generated by Django 3.0.5 on 2021-03-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_casing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='type',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('A', 'Apertura'), ('C', 'Cierre')], max_length=1, verbose_name='Tipo proceso'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='type_bank',
            field=models.CharField(blank=True, choices=[('1', 'Banco de Credito del Peru'), ('2', 'Banco de la Nación del Peru'), ('3', 'Interbank'), ('4', 'BBVA Continental')], max_length=1, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='type_payment',
            field=models.CharField(choices=[('E', 'Efectivo'), ('D', 'Deposito'), ('C', 'Credito')], max_length=1, verbose_name='Tipo proceso'),
        ),
    ]
